import { Context } from "hono";
import { ContentfulStatusCode } from "hono/utils/http-status";

// ROUTES
export function statusReponse(status: string, message: {} | string, statusCode: ContentfulStatusCode, context: Context) {
    return context.json({
        status,
        message
    }, statusCode)
}

export enum HttpStatusCode {
    Continue = 100,
    SwitchingProtocols = 101,
    Processing = 102,
    EarlyHints = 103,
    OK = 200,
    Created = 201,
    Accepted = 202,
    NonAuthoritativeInformation = 203,
    NoContent = 204,
    ResetContent = 205,
    PartialContent = 206,
    MultiStatus = 207,
    AlreadyReported = 208,
    IMUsed = 226,
    MultipleChoices = 300,
    MovedPermanently = 301,
    Found = 302,
    SeeOther = 303,
    NotModified = 304,
    UseProxy = 305,
    TemporaryRedirect = 307,
    PermanentRedirect = 308,
    BadRequest = 400,
    Unauthorized = 401,
    PaymentRequired = 402,
    Forbidden = 403,
    NotFound = 404,
    MethodNotAllowed = 405,
    NotAcceptable = 406,
    ProxyAuthenticationRequired = 407,
    RequestTimeout = 408,
    Conflict = 409,
    Gone = 410,
    LengthRequired = 411,
    PreconditionFailed = 412,
    PayloadTooLarge = 413,
    URITooLong = 414,
    UnsupportedMediaType = 415,
    RangeNotSatisfiable = 416,
    ExpectationFailed = 417,
    ImATeapot = 418,
    MisdirectedRequest = 421,
    UnprocessableEntity = 422,
    Locked = 423,
    FailedDependency = 424,
    TooEarly = 425,
    UpgradeRequired = 426,
    PreconditionRequired = 428,
    TooManyRequests = 429,
    RequestHeaderFieldsTooLarge = 431,
    UnavailableForLegalReasons = 451,
    InternalServerError = 500,
    NotImplemented = 501,
    BadGateway = 502,
    ServiceUnavailable = 503,
    GatewayTimeout = 504,
    HTTPVersionNotSupported = 505,
    VariantAlsoNegotiates = 506,
    InsufficientStorage = 507,
    LoopDetected = 508,
    NotExtended = 510,
    NetworkAuthenticationRequired = 511
}

export enum NamesiloResponseCode {
    HTTPS_NOT_USED = 101,
    NO_VERSION_SPECIFIED = 102,
    INVALID_API_VERSION = 103,
    NO_TYPE_SPECIFIED = 104,
    INVALID_API_TYPE = 105,
    NO_OPERATION_SPECIFIED = 106,
    INVALID_API_OPERATION = 107,
    MISSING_PARAMETERS = 108,
    NO_API_KEY_SPECIFIED = 109,
    INVALID_API_KEY = 110,
    INVALID_USER = 111,
    API_NOT_AVAILABLE_TO_SUB_ACCOUNTS = 112,
    API_ACCESS_DENIED_FOR_IP = 113,
    INVALID_DOMAIN_SYNTAX = 114,
    CENTRAL_REGISTRY_NOT_RESPONDING = 115,
    INVALID_SANDBOX_ACCOUNT = 116,
    INVALID_CREDIT_CARD_PROFILE = 117,
    UNVERIFIED_CREDIT_CARD_PROFILE = 118,
    INSUFFICIENT_ACCOUNT_FUNDS = 119,
    API_KEY_MUST_BE_GET = 120,
    DOMAIN_NOT_ACTIVE_OR_NOT_OWNED = 200,
    INTERNAL_SYSTEM_ERROR = 201,
    GENERAL_ERROR = 210,
    DOMAIN_ALREADY_AUTO_RENEW = 250,
    DOMAIN_ALREADY_NOT_AUTO_RENEW = 251,
    DOMAIN_ALREADY_LOCKED = 252,
    DOMAIN_ALREADY_UNLOCKED = 253,
    NAMESERVER_UPDATE_ERROR = 254,
    DOMAIN_ALREADY_PRIVATE = 255,
    DOMAIN_ALREADY_NOT_PRIVATE = 256,
    DOMAIN_PROCESSING_ERROR = 261,
    DOMAIN_ALREADY_ACTIVE = 262,
    INVALID_NUMBER_OF_YEARS = 263,
    DOMAIN_RENEWAL_ERROR = 264,
    DOMAIN_TRANSFER_ERROR = 265,
    NO_DOMAIN_TRANSFER_EXISTS = 266,
    INVALID_DOMAIN_NAME_OR_TLD = 267,
    DNS_MODIFICATION_ERROR = 280,
    SUCCESSFUL_API_OPERATION = 300,
    SUCCESSFUL_REGISTRATION_WITH_INVALID_HOSTS = 301,
    SUCCESSFUL_ORDER_WITH_INVALID_CONTACT_INFO = 302,
    EXISTING_API_REQUEST_PROCESSING = 400,
}